name:               "Insight Lane"
description:        "Open source platform for analyzing risk on road networks"

baseurl: "/blog"

url:                ""
author:             "bpben"
email:              "info@insightlane.org"
gravatar_hash:      ""
twitter:            "insight_lane"
github:             "insight-lane"
disqus_shortname:   ""

background:         "/resources/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/#about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
