name:               "Insight Lane"
description:        "Open source platform for analyzing risk on road networks"

url:                ""
author:             "bpben"
email:              "info@insightlane.org"
gravatar_hash:      ""
twitter:            "insight_lane"
github:             "insight-lane"
slack:             "https://join.slack.com/t/insightlane/shared_invite/zt-ewlvaic7-ymYlps33v2M2~RhC4DFRGg"
disqus_shortname:   ""

background:         "/resources/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
